[default]
secret_key = "rzqmcGmlN8LuIelc5KlHEug/x+14Ap9c4T7oxJPFE2s="

[default.oauth.github]
provider = "GitHub"
client_id = "750bcd88906f9aab698f"
client_secret = "5044bbf667e4aec0beb8bf2912614d24e1f88be9"
redirect_uri = "https://sogrim.herokuapp.com/auth/github"