[package]
name = "sogrim-server"
version = "1.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
colored = "2"
mongodb = "2.7"
bson = "2.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = "1.32"
actix-rt = "2.9"
actix-web = "4.4"
actix-web-lab = "0.20"
actix-cors = "0.6"
futures-util = "0.3"
jsonwebtoken = "9.1"
env_logger = "0.10"
lazy_static = "1.4"
petgraph = "0.6"
regex = "1.9"
reqwest = { version = "0.11", features = ["json"] }

[build-dependencies]
dotenvy = "0.15"

[dev-dependencies]
# these crates are used for key generation to encrypt JWT in tests
base64 = "0.21.2"
rand = "0.8.5"
rsa = "0.9.2"
