[package]
name = "sogrim-server"
version = "1.0.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
colored = "2"
mongodb = "2.1"
bson = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-rt = "2.2"
actix-web = "4.0"
actix-web-lab = "0.9"
actix-cors = "0.6"
actix-service = "2.0"
futures-util = "0.3"
jsonwebtoken = "8.0"
jsonwebtoken-google = {version = "0.1", features = ["test-helper"]}
env_logger = "0.9"
toml = "0.5"
dotenv = "0.15"
lazy_static = "1.4"
petgraph = "0.6"
derive_more = "0.99"

[patch.crates-io]
jsonwebtoken-google = { git = 'https://github.com/cheetah-games/jsonwebtoken-google' }
