[package]
name = "sogrim-server"
version = "1.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
colored = "2"
mongodb = "2.4"
bson = "2.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = "1.24"
actix-rt = "2.2"
actix-web = "4.3"
actix-web-lab = "0.9"
actix-cors = "0.6"
futures-util = "0.3"
jsonwebtoken = "8.0"
jsonwebtoken-google = "0.1"
env_logger = "0.9"
petgraph = "0.6"
regex = "1.7.1"

[build-dependencies]
dotenvy = "0.15"

[dev-dependencies.jsonwebtoken-google]
version = "0.1" 
features = ["test-helper"]
