[package]
name = "sogrim-server"
version = "1.0.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
colored = "2"
mongodb = "2.1"
bson = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-rt = "2.2.0"
actix-web = "4.0.0-rc.2"
actix-web-lab = "0.9.0"
actix-cors = "0.6.0-beta.9"
actix-service = "2.0.1"
futures-util = "0.3.17"
jsonwebtoken = "8.0"
jsonwebtoken-google = {version = "0.1", features = ["test-helper"]}
env_logger = "0.9.0"
toml = "0.5.8"
dotenv = "0.15.0"
lazy_static = "1.4.0"
petgraph = "0.6.0"

[patch.crates-io]
jsonwebtoken-google = { git = 'https://github.com/cheetah-games/jsonwebtoken-google' }
