on:
  push:
    branches:
      - master # TODO someday will probably need to be renamed into 'main'
    paths:
      - "packages/server/**" # Trigger this CI flow if changes were made to server subtree ONLY (code coverage is only supported for server for now)

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --manifest-path packages/server/Cargo.toml --verbose --all-features --workspace --timeout 120 --ignore-tests --out Xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
