on:
  push:
    branches:
      - master # TODO someday will probably need to be renamed into 'main'

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: norelease # Never generate a release unless explicitly specified with PR labels.
