on:
  push:
    branches:
      - master # TODO someday will probably need to be renamed into 'main'
    paths:
      - "packages/server/**" # Trigger this CI flow if changes were made to server subtree ONLY

name: Deploy server to Heroku

jobs:
  deploy-server:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "sogrim"
          heroku_email: "benick12@gmail.com"
          procfile: "web: PORT=$PORT PROFILE=staging ./target/release/sogrim-server"
          appdir: "packages/server"
