on:
  pull_request:
    branches:
      - master # TODO someday will probably need to be renamed into 'main'
    paths:
      - "**"
      - "!packages/server/**" # Trigger this CI flow if changes were made to ANYTHING BUT server

name: Fake-CI # TODO maybe rename this from "fake" to something more informative

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "IRRELEVANT"

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - run: echo "IRRELEVANT"

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - run: echo "IRRELEVANT"

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_CLIENT_API_KEY}}
          heroku_app_name: "sogrim-app"
          heroku_email: "nissan.ohana@gmail.com"
          appdir: "packages/sogrim-app"
